version: '3'

services:
  resizer:
    build: .
    volumes:
      - "./_out:/out"
    ports:
      - "3000:3000"
    environment:
    - SERVER_ADDR=0.0.0.0:3000
    - RESIZE_WORKER_COUNT=10
    - FILE_SAVE_WORKER_COUNT=20
    - REQUEST_IMG_WORKER_COUNT=10
    - RESIZE_CHANNEL_SIZE=10
    - FILE_SAVE_CHANNEL_SIZE=20
    - REQUEST_IMG_CHANNEL_SIZE=10
    - JOB_TIMEOUT_SEC=10
    - FILE_SAVE_DIR=/out